# Generated by Django 5.2 on 2025-05-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0004_nippomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
