# Generated by Django 5.2 on 2025-05-01 23:57

import nippo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0006_nippomodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(default=nippo.models.slug_maker, max_length=20, unique=True),
        ),
    ]
